---
# Resource quota for monitoring namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-stack
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
spec:
  hard:
    # Compute resources
    requests.cpu: "2000m"
    requests.memory: "4Gi"
    requests.ephemeral-storage: "10Gi"
    limits.cpu: "4000m"
    limits.memory: "8Gi"
    limits.ephemeral-storage: "20Gi"
    
    # Object counts
    count/pods: "20"
    count/services: "10"
    count/secrets: "10"
    count/configmaps: "20"
    count/persistentvolumeclaims: "10"
    count/deployments.apps: "5"
    count/replicasets.apps: "10"
    
    # Storage
    requests.storage: "100Gi"
    
    # Network policies
    count/networkpolicies.networking.k8s.io: "20"
    
    # Service accounts
    count/serviceaccounts: "10"
---
# LimitRange for monitoring namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limits
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-stack
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
spec:
  limits:
  # Default container limits
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
      ephemeral-storage: "100Mi"
    max:
      cpu: "2000m"
      memory: "4Gi"
      ephemeral-storage: "10Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
      ephemeral-storage: "50Mi"
  
  # Pod limits
  - type: Pod
    max:
      cpu: "4000m"
      memory: "8Gi"
      ephemeral-storage: "20Gi"
  
  # PVC limits
  - type: PersistentVolumeClaim
    max:
      storage: "50Gi"
    min:
      storage: "1Gi"
---
# Pod Disruption Budget for Prometheus
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-pdb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
---
# Pod Disruption Budget for AlertManager
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alertmanager-pdb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: alerting
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
---
# Pod Disruption Budget for Grafana
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana-pdb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
