---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner-system
  labels:
    name: gitlab-runner-system
    security.istio.io/tlsMode: istio
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    app.kubernetes.io/name: gitlab-runner-controller
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # Network policies enforced
    security.perihelion.io/network-policy: "strict"
    # Monitoring enabled
    monitoring.perihelion.io/enabled: "true"
    # Security scanning enabled
    security.perihelion.io/scan-enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runners
  labels:
    name: gitlab-runners
    security.istio.io/tlsMode: istio
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    app.kubernetes.io/name: gitlab-runners
    app.kubernetes.io/component: compute
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # Network policies enforced
    security.perihelion.io/network-policy: "strict"
    # Monitoring enabled
    monitoring.perihelion.io/enabled: "true"
    # Security scanning enabled
    security.perihelion.io/scan-enabled: "true"
    # Resource quotas enforced
    resource.perihelion.io/quota-enabled: "true"
