---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    security.istio.io/tlsMode: istio
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    app.kubernetes.io/name: logging-stack
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # Network policies enforced
    security.perihelion.io/network-policy: "strict"
    # Monitoring enabled
    monitoring.perihelion.io/enabled: "true"
    # Security scanning enabled
    security.perihelion.io/scan-enabled: "true"
    # Resource quotas enforced
    resource.perihelion.io/quota-enabled: "true"
    # Note: Logging requires privileged access for log collection
