---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner-controller-metrics
  namespace: gitlab-runner-system
  labels:
    app.kubernetes.io/name: gitlab-runner-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gitlab-runner-controller
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner-controller-health
  namespace: gitlab-runner-system
  labels:
    app.kubernetes.io/name: gitlab-runner-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: perihelion-auth-manager
    app.kubernetes.io/managed-by: kubectl
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gitlab-runner-controller
  ports:
  - name: health
    port: 8081
    targetPort: health
    protocol: TCP
  sessionAffinity: None
