---
# External Secrets Operator namespace
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: perihelion-auth-manager
---
# Service Account for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: perihelion-auth-manager
automountServiceAccountToken: true
---
# ClusterRole for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-operator
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: perihelion-auth-manager
rules:
# Secrets management
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ConfigMaps for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# External Secrets CRDs
- apiGroups: ["external-secrets.io"]
  resources: ["*"]
  verbs: ["*"]
# Service accounts for authentication
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
# ClusterRoleBinding for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-operator
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: perihelion-auth-manager
subjects:
- kind: ServiceAccount
  name: external-secrets-operator
  namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: external-secrets-operator
  apiGroup: rbac.authorization.k8s.io
---
# Deployment for External Secrets Operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: perihelion-auth-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-secrets-operator
        app.kubernetes.io/component: security
        app.kubernetes.io/part-of: perihelion-auth-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: external-secrets-operator
      automountServiceAccountToken: true
      
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      
      containers:
      - name: external-secrets-operator
        image: ghcr.io/external-secrets/external-secrets:v0.9.11
        imagePullPolicy: IfNotPresent
        
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 100Mi
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 1Gi
        
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        
        args:
        - --log-level=info
        - --log-format=json
        - --metrics-addr=:8080
        - --concurrent=5
        
        env:
        - name: ES_CONTROLLER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 100Mi
---
# Service for External Secrets Operator metrics
apiVersion: v1
kind: Service
metadata:
  name: external-secrets-operator-metrics
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/component: security
    app.kubernetes.io/part-of: perihelion-auth-manager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: external-secrets-operator
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
